In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import cv2

In [3]:
# load dataset
data = pd.read_csv(r'image_labels_paths.csv')
data.head()

,Fractured,Non-Fractured
0,X-ray Imaging Dataset for Detecting Fractured ...,X-ray Imaging Dataset for Detecting Fractured ...
1,X-ray Imaging Dataset for Detecting Fractured ...,X-ray Imaging Dataset for Detecting Fractured ...
2,X-ray Imaging Dataset for Detecting Fractured ...,X-ray Imaging Dataset for Detecting Fractured ...
3,X-ray Imaging Dataset for Detecting Fractured ...,X-ray Imaging Dataset for Detecting Fractured ...
4,X-ray Imaging Dataset for Detecting Fractured ...,X-ray Imaging Dataset for Detecting Fractured ...

In [8]:
# Def Image Processing 
def image_processing(img_path):
    img = cv2.imread(img_path)
    # convert to grayscale
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # resize to 100*100
    img_res = cv2.resize(img_gray, (100,100))
    # convert to numpy array
    img_ary = np.array(img_res).flatten()
    # convert to dataFrame
    img_df = pd.DataFrame(img_ary).T
    img_df.head()
    return img_df

In [9]:
image_processing(data['Fractured'][0])

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
final_df = pd.DataFrame()

In [18]:
# for feature in data.columns: 
#     for img in data[feature]:
#         ret_df = image_processing(img)
#         final_df = pd.concat([final_df, ret_df])

for img in data['Fractured']:
    df_x = image_processing(img)
    final_df = pd.concat([final_df, df_x])
final_df['label'] = 'Fractured'

In [19]:
final_df.head()

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fractured
0,26,26,24,21,21,21,21,21,21,21,...,32,33,31,31,32,34,33,36,32,Fractured
0,0,0,0,0,0,0,8,9,17,23,...,0,0,0,0,0,0,0,0,0,Fractured
0,0,0,0,0,0,0,0,0,0,0,...,189,175,166,152,144,139,145,153,173,Fractured
0,0,0,0,0,0,0,0,0,4,6,...,0,0,0,1,2,1,4,106,211,Fractured

In [20]:
final_df.index = range(len(final_df))

In [21]:
final_df.to_csv('bone_fractured_unlabelled.csv', index = False)

In [13]:
final_df.head()

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fractured
1,26,26,24,21,21,21,21,21,21,21,...,32,33,31,31,32,34,33,36,32,Fractured
2,0,0,0,0,0,0,8,9,17,23,...,0,0,0,0,0,0,0,0,0,Fractured
3,0,0,0,0,0,0,0,0,0,0,...,189,175,166,152,144,139,145,153,173,Fractured
4,0,0,0,0,0,0,0,0,4,6,...,0,0,0,1,2,1,4,106,211,Fractured

In [11]:
final_dfx = pd.DataFrame()

In [12]:
for img in data['Non-Fractured']:
    df_x = image_processing(img)
    final_dfx = pd.concat([final_dfx, df_x])

final_dfx['label'] = 'Non-Fractured'

In [22]:
# concating final_df and final_dfx

final_images_df = pd.concat([final_df, final_dfx])

In [23]:
final_df.shape

(4650, 10001)

In [24]:
final_dfx.shape

(4650, 10001)

In [26]:
final_images_df.to_csv('final_images_df.csv', index = False)