In [1]:
# import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data = pd.read_csv(r'final_images_df.csv')
data.head()

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fractured
1,26,26,24,21,21,21,21,21,21,21,...,32,33,31,31,32,34,33,36,32,Fractured
2,0,0,0,0,0,0,8,9,17,23,...,0,0,0,0,0,0,0,0,0,Fractured
3,0,0,0,0,0,0,0,0,0,0,...,189,175,166,152,144,139,145,153,173,Fractured
4,0,0,0,0,0,0,0,0,4,6,...,0,0,0,1,2,1,4,106,211,Fractured

In [3]:
# Split x and y and from there create x_train, x_test, y_train, y_test

In [4]:
# import classifier
# xgb
# lightgbm

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [6]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [7]:
# split into x and y 
data.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '9991', '9992', '9993', '9994', '9995', '9996', '9997', '9998', '9999',
       'label'],
      dtype='object', length=10001)

In [8]:
# mapping the label

enc_label = {'Fractured': 0, 'Non-Fractured': 1}

In [9]:
data['label'] = data['label'].map(enc_label)

In [10]:
x = data.drop('label', axis = 1)
y = data.label

In [11]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,26,26,24,21,21,21,21,21,21,21,...,33,32,33,31,31,32,34,33,36,32
2,0,0,0,0,0,0,8,9,17,23,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,189,175,166,152,144,139,145,153,173
4,0,0,0,0,0,0,0,0,4,6,...,1,0,0,0,1,2,1,4,106,211

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [13]:
# Split into train test split 
from sklearn.model_selection import train_test_split

In [14]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [16]:
x_train.shape

(7440, 10000)

In [17]:
x_test.shape

(1860, 10000)

In [18]:
# creating a model_dictionary

# model_dict = {
#     'lr_model': LogisticRegression(),
#     'dt_model': DecisionTreeClassifier(),
#     'svc_model': SVC(),
#     'knn_model': KNeighborsClassifier(),
#     'xgb_model' : XGBClassifier(max_depth = 4, n_estimators = 100, subsample = 0.8, colsample_bytree = 0.8, tree_method = 'hist'),
#     'lgb_model': LGBMClassifier()
# }


# xgb = XGBClassifier(
#     max_depth=4,             # reduce tree depth
#     n_estimators=100,        # fewer trees
#     subsample=0.8,           # use a subset of training data per tree
#     colsample_bytree=0.8,    # use a subset of features per tree
#     tree_method='hist'       # efficient histogram-based method
# )

In [19]:
data.duplicated().sum()

0

In [20]:
data.isna().sum()

0        0
1        0
2        0
3        0
4        0
        ..
9996     0
9997     0
9998     0
9999     0
label    0
Length: 10001, dtype: int64

In [21]:
# importing accuracy score
from sklearn.metrics import accuracy_score

In [22]:
accs = []

In [23]:
# for name, model in model_dict.items():
#     model.fit(x_train, y_train)
#     y_pred = model.predict(x_test)
#     ac = accuracy_score(y_test, y_pred)
#     accs.append(ac)

In [24]:
# plt.plot(model_dict.keys(), accs, marker = 'D')
# plt.grid()

In [25]:
lr_model = LogisticRegression()

In [26]:
lr_model.fit(x_train, y_train)

C:\Users\prash\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
y_pred1 = lr_model.predict(x_test)

In [28]:
lr_accuracy = accuracy_score(y_test, y_pred1)

In [29]:
print(lr_accuracy)

0.6903225806451613

In [30]:
dt_model = DecisionTreeClassifier()

In [31]:
dt_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [32]:
y_pred2 = dt_model.predict(x_test)

In [33]:
dt_accuracy = accuracy_score(y_test, y_pred2)
dt_accuracy

0.7494623655913979

In [34]:
svc_model = SVC()

In [35]:
svc_model.fit(x_train, y_train)

SVC()

In [36]:
y_pred3 = svc_model.predict(x_test)

In [37]:
svc_accuracy = accuracy_score(y_test, y_pred3)
svc_accuracy

0.9059139784946236

In [38]:
knn_model = KNeighborsClassifier()

In [39]:
knn_model.fit(x_train, y_train)

KNeighborsClassifier()

In [40]:
y_pred4 = knn_model.predict(x_test)

In [41]:
knn_accuracy = accuracy_score(y_test, y_pred4)
knn_accuracy

0.896774193548387

In [42]:
# creating model for xgboost and lightgbm

xgb_model = XGBClassifier()

In [43]:
xgb_model.fit(x_train, y_train)

XGBoostError: [09:20:40] C:\actions-runner\_work\xgboost\xgboost\src\common\io.h:389: bad_malloc: Failed to allocate 2554112736 bytes.

In [ ]:
y_pred5 = xgb_model.predict(x_test)

In [ ]:
xgb_accuracy = accuracy_score(y_test, y_pred5)
xgb_accuracy*100

In [ ]:
lgb_model = LGBMClassifier()

In [ ]:
lgb_model.fit(x_train, y_train)

In [ ]:
y_pred6 = lgb_model.predict(x_test)

In [ ]:
lgb_accuracy = accuracy_score(y_test, y_pred6)
lgb_accuracy

In [ ]:
# best model is xgb model so we want to save it as a model 
import joblib

In [ ]:
joblib.dump(xgb_model, 'bone_fracture_xgb_model.pt')